name: ftu_lms
version: 0.0.1+11
publish_to: none
description: The Learning Management System.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  get_storage: ^2.0.3
  watcher: ^1.1.0
  firebase_core_platform_interface: 5.0.0
  cupertino_icons: ^1.0.2
  fimber: ^0.6.6
  flutter_hooks: ^0.18.5+1
  visibility_detector: ^0.3.3
  flutter_keyboard_visibility: ^5.3.0
  lottie: ^1.4.3
  flutter_svg: ^1.1.5
  shimmer: ^2.0.0
  intl: ^0.17.0
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  path_provider_android: ^2.0.20
  path_provider_ios: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.10.0
  dio: ^4.0.6
  http_mock_adapter: ^0.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.1.0
  flutter_slidable: ^2.0.0
  auto_size_text: ^3.0.0
  flutter_cached_pdfview: ^0.4.2
  connectivity_plus: ^2.3.7
  flutter_local_notifications: ^11.0.1
  flutter_native_timezone: ^2.0.0
  equatable: ^2.0.5
  file_picker: ^5.0.1
  theme_tailor_annotation: ^1.0.3
  cached_network_image: ^3.3.1
  carousel_slider: ^4.1.1
  get: ^4.6.5
  dotted_line: ^3.1.0
  local_auth: ^2.1.2
  cryptography_flutter: ^2.0.2
  video_player: ^2.4.7
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  flutter_easyloading: ^3.0.5
  status_bar_control: 3.2.1
  dart_extensions: ^2.2.0
  meta: ^1.8.0
  get_cli: ^1.8.1
  url_launcher: 6.1.7
  flutter_datetime_picker:
    git:
      url: https://github.com/ryojiro/flutter_datetime_picker.git
      ref: 32ea47240c10469ad31db0084f5d9b7a12d16e01
  onesignal_flutter: ^3.5.0
  gallery_saver: 2.3.2
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar:
    git:
      url: https://github.com/DanhDue/animated-bottom-navigation-bar-flutter.git
      ref: disable-active-scale-animation
  sliding_up_panel2:
    git:
      url: https://github.com/D3FOutsourcing/sliding_up_panel.git
      ref: scrolling-in-the-minimized-state
  annotations:
    path: lib/utils/annotations/
  jiffy:
    git:
      url: https://github.com/D3FOutsourcing/jiffy.git
      ref: master
  cli_script: ^0.3.1
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.9.0
  webview_flutter: ^4.5.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  shared_preferences_helper: ^0.0.3
  melos: ^3.4.0
  week_of_year: ^2.2.0
  searchfield: ^1.0.5
  http: ^0.13.6
  mime: ^1.0.0



dev_dependencies:
  test: ^1.21.4
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.0.1
  json_serializable: ^6.4.1
  hive_generator: ^2.0.0
  freezed: ^2.1.0+1flutter
  theme_tailor: ^1.0.6
  retrofit_generator: ^4.2.0
  flutter_native_splash: ^2.2.16
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  hive_test: ^1.0.1
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  generators: 
    path: lib/utils/generators/

module: 
  androidX: true

dartfmt: 
  line_length: 99

flutter_gen: 
  output: lib/generated/
  integrations: 
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true
    json: true
  assets: 
    outputs: 
      class_name: Assets
      style: dot-delimiter
      package_parameter_enabled: false
    enabled: true
  colors: 
    outputs: 
      class_name: LMSColors
      style: dot-delimiter
      package_parameter_enabled: false
    inputs: 
      - assets/colors/colors.xml
    enable: true
  fonts: 
    outputs: 
      class_name: LMSFontFamily
    enabled: true
  line_length: 99

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/lotties/
    - assets/jsons/
    - assets/Icon/
    - assets/animation/











  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: SfCompactRegular
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Regular.ttf
    - family: SfCompactMedium
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Medium.ttf
    - family: SfCompactSemiBold
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Semibold.ttf
    - family: SfCompactBold
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Bold.ttf




