// Copyright (c) 2022, one of the D3F outsourcing projects. All rights reserved.

// coverage:ignore-file

part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const CHECKIN = _Paths.CHECKIN;
  static const SETTINGS = _Paths.SETTINGS;
  static const PERSONAL = _Paths.PERSONAL;
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const SCHEDULE_TIME = _Paths.SCHEDULE_TIME;
  static const PROFILE = _Paths.PROFILE;
  static const PASSWORD_EDITION = _Paths.PASSWORD_EDITION;
  static const PROFILE_EDITION = _Paths.PROFILE_EDITION;
  static const TESTING_PLANING = _Paths.TESTING_PLANING;
  static const TRAINING_POINTS = _Paths.TRAINING_POINTS;
  static const CONSCIOUSNESS_EVALUATION = _Paths.CONSCIOUSNESS_EVALUATION;
  static const LEARNING_RESULTS = _Paths.LEARNING_RESULTS;
  static const SEMESTER_POINTS = _Paths.SEMESTER_POINTS;
  static const EDUCATION_PROGRAM = _Paths.EDUCATION_PROGRAM;
  static const TUITION = _Paths.TUITION;
  static const FINANCE_OVERVIEW = _Paths.FINANCE_OVERVIEW;
  static const FINANCE_BY_SEMESTER = _Paths.FINANCE_BY_SEMESTER;
  static const SCHEDULE_DAILY = _Paths.SCHEDULE_DAILY;
  static const APP_INFORMATION = _Paths.APP_INFORMATION;
  static const INFINITE_LIST_SAMPLE = _Paths.INFINITE_LIST_SAMPLE;
  static const SCIENTIFIC_RESEARCH = _Paths.SCIENTIFIC_RESEARCH;
  static const ITEM_SCIENTIFIC_RESEARCH = _Paths.ITEM_SCIENTIFIC_RESEARCH;
  static const ELEARNING = _Paths.ELEARNING;
  static const DOCUMENT_FORM = _Paths.DOCUMENT_FORM;
  static const ONE_GATE = _Paths.ONE_GATE;
  static const LIST_TEACHER_INFO = _Paths.LIST_TEACHER_INFO;
  static const CREATE_NEW_FORM = _Paths.CREATE_NEW_FORM;
  static const LIST_REQUEST_FORM = _Paths.LIST_REQUEST_FORM;
  static const DOCUMENT_FORM_ITEM = _Paths.DOCUMENT_FORM_ITEM;
  static const SERVICE_REQUEST_LIST = _Paths.SERVICE_REQUEST_LIST;
  static const ALL_SERVICE_REQUEST_LIST = _Paths.ALL_SERVICE_REQUEST_LIST;
  static const WAITING_SERVICE_REQUEST_LIST = _Paths.WAITING_SERVICE_REQUEST_LIST;
  static const APPROVED_SERVICE_REQUEST_LIST = _Paths.APPROVED_SERVICE_REQUEST_LIST;
  static const REJECTED_SERVICE_REQUEST_LIST = _Paths.REJECTED_SERVICE_REQUEST_LIST;
  static const NOTIFICATION_DETAILS = _Paths.NOTIFICATION_DETAILS;
  static const DISCUSS_FEEDBACK = _Paths.DISCUSS_FEEDBACK;
  static const CREATE_NEW_CONVERSATION = _Paths.CREATE_NEW_CONVERSATION;
  static const DETAIL_CONVERSATION = _Paths.DETAIL_CONVERSATION;
  static const COURSE_POINTS = _Paths.COURSE_POINTS;
  static const BILL_PAYMENT = _Paths.BILL_PAYMENT;
  static const PRACTICE_POINT_OVERVIEW = _Paths.PRACTICE_POINT_OVERVIEW;
  static const PRACTICE_POINT_DETAIL = _Paths.PRACTICE_POINT_DETAIL;
  static const LIST_CERTIFICATES = _Paths.LIST_CERTIFICATES;
  static const CREATE_NEW_CERTIFICATE = _Paths.CREATE_NEW_CERTIFICATE;
  static const WORKING_PROCESS = _Paths.WORKING_PROCESS;
  static const LEARNING_PROCESS = _Paths.LEARNING_PROCESS;
  static const LIST_WORKING_PROCESS = _Paths.LIST_WORKING_PROCESS;
  static const LANGUAGE_PROCESS = _Paths.LANGUAGE_PROCESS;
  static const LEARNING_PROFILE = _Paths.LEARNING_PROFILE;
  static const CREATE_WORKING_PROCESS = _Paths.CREATE_WORKING_PROCESS;
  static const CREATE_LANGUAGE_PROCESS = _Paths.CREATE_LANGUAGE_PROCESS;
  static const CREATE_LEARNING_PROCESS = _Paths.CREATE_LEARNING_PROCESS;
  static const REWARD_DISCIPLINE = _Paths.REWARD_DISCIPLINE;
  static const REWARD = _Paths.REWARD;
  static const DISCIPLINE = _Paths.DISCIPLINE;
  static const SURVEY_RESULT = _Paths.SURVEY_RESULT;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const SURVEY_ITEM = _Paths.SURVEY_ITEM;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const DASHBOARD = '/dashboard';
  static const NOTIFICATION = '/notification';
  static const CHECKIN = '/checkin';
  static const SETTINGS = '/settings';
  static const PERSONAL = '/personal';
  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const SCHEDULE_TIME = '/schedule-time';
  static const PROFILE = '/profile';
  static const PASSWORD_EDITION = '/password-edition';
  static const PROFILE_EDITION = '/profile-edition';
  static const TESTING_PLANING = '/testing-planing';
  static const TRAINING_POINTS = '/training-points';
  static const CONSCIOUSNESS_EVALUATION = '/consciousness-evaluation';
  static const LEARNING_RESULTS = '/learning-results';
  static const SEMESTER_POINTS = '/semester-points';
  static const EDUCATION_PROGRAM = '/education-program';
  static const TUITION = '/tuition';
  static const FINANCE_OVERVIEW = '/finance-overview';
  static const FINANCE_BY_SEMESTER = '/finance-by-semester';
  static const SCHEDULE_DAILY = '/schedule-daily';
  static const APP_INFORMATION = '/app-information';
  static const INFINITE_LIST_SAMPLE = '/infinite-list-sample';
  static const SCIENTIFIC_RESEARCH = '/scientific-research';
  static const ITEM_SCIENTIFIC_RESEARCH = '/item-scientific-research';
  static const ELEARNING = '/elearning';
  static const DOCUMENT_FORM = '/document-form';
  static const ONE_GATE = '/one-gate';
  static const LIST_TEACHER_INFO = '/list-teacher-info';
  static const CREATE_NEW_FORM = '/create-new-form';
  static const LIST_REQUEST_FORM = '/list-request-form';
  static const DOCUMENT_FORM_ITEM = '/document-form-item';
  static const SERVICE_REQUEST_LIST = '/service-request-list';
  static const ALL_SERVICE_REQUEST_LIST = '/all-service-request-list';
  static const WAITING_SERVICE_REQUEST_LIST = '/waiting-service-request-list';
  static const APPROVED_SERVICE_REQUEST_LIST = '/approved-service-request-list';
  static const REJECTED_SERVICE_REQUEST_LIST = '/rejected-service-request-list';
  static const TEMPLE = '/temple';
  static const NOTIFICATION_DETAILS = '/notification-details';
  static const DISCUSS_FEEDBACK = '/discuss-feedback';
  static const CREATE_NEW_CONVERSATION = '/create-new-conversation';
  static const DETAIL_CONVERSATION = '/detail-conversation';
  static const COURSE_POINTS = '/course-points';
  static const BILL_PAYMENT = '/bill-payment';
  static const PRACTICE_POINT_OVERVIEW = '/practice-point-overview';
  static const PRACTICE_POINT_DETAIL = '/practice-point-detail';
  static const LIST_CERTIFICATES = '/list-certificates';
  static const CREATE_NEW_CERTIFICATE = '/create-new-certificate';
  static const WORKING_PROCESS = '/working-process';
  static const LEARNING_PROCESS = '/learning-process';
  static const LIST_WORKING_PROCESS = '/list-working-process';
  static const LANGUAGE_PROCESS = '/language-process';
  static const LEARNING_PROFILE = '/learning-profile';
  static const CREATE_WORKING_PROCESS = '/create-working-process';
  static const CREATE_LANGUAGE_PROCESS = '/create-language-process';
  static const CREATE_LEARNING_PROCESS = '/create-learning-process';
  static const REWARD_DISCIPLINE = '/reward-discipline';
  static const REWARD = '/reward';
  static const DISCIPLINE = '/discipline';
  static const SURVEY_RESULT = '/survey-result';
  static const ACCOUNT = '/account';
  static const SURVEY_ITEM = '/survey-item';
}
